'use client';

import { z } from 'zod';
import { useForm } from 'react-hook-form';
import { useMemo, useEffect } from 'react';
import { zodResolver } from '@hookform/resolvers/zod';

import Box from '@mui/material/Box';
import Card from '@mui/material/Card';
import Grid from '@mui/material/Grid';
import Stack from '@mui/material/Stack';
import MenuItem from '@mui/material/MenuItem';
import Typography from '@mui/material/Typography';
import LoadingButton from '@mui/lab/LoadingButton';

import { paths } from 'src/routes/paths';
import { useRouter } from 'src/routes/hooks';

import { createBusinessVisaRequest, updateBusinessVisaRequest } from 'src/utils/apiHelper';

import { toast } from 'src/components/snackbar';
import { Form, Field } from 'src/components/hook-form';

// ----------------------------------------------------------------------

const BusinessVisaSchema = z.object({
  requestNumber: z.string().optional(), // requestNumber is auto-generated by DB; keep optional for editing
  applicantName: z.string().min(1, { message: 'Applicant name is required!' }),
  applicantCompany: z.string().optional(),
  nationality: z.string().min(1, { message: 'Nationality is required!' }),
  passportNumber: z.string().min(1, { message: 'Passport number is required!' }),
  passportExpiryDate: z.string().min(1, { message: 'Passport expiry date is required!' }),
  purpose: z.string().min(1, { message: 'Purpose is required!' }),
  durationDays: z.coerce.number().min(1, { message: 'Duration must be at least 1 day!' }),
  requestedDate: z.string().min(1, { message: 'Requested date is required!' }),
  expectedArrivalDate: z.string().optional(),
  passportCopyUrl: z.string().optional(),
  letterOfIntentUrl: z.string().optional(),
  companyCrUrl: z.string().optional(),
  invitationLetterUrl: z.string().optional(),
  visaFee: z.coerce.number().min(0, { message: 'Visa fee must be 0 or greater!' }),
  processingFee: z.coerce.number().min(0).optional(),
  totalAmount: z.coerce.number().min(0, { message: 'Total amount is required!' }),
  currencyCode: z.string().min(1, { message: 'Currency is required!' }),
  status: z.enum(['Pending', 'Approved', 'Processed', 'Issued', 'Rejected', 'Cancelled']),
  assignedTo: z.string().optional(),
  remarks: z.string().optional(),
  invoiceId: z.string().optional(),
});

// ----------------------------------------------------------------------

export function BusinessVisaNewEditForm({ currentRequest }) {
  const router = useRouter();

  const defaultValues = useMemo(
    () => ({
      requestNumber: currentRequest?.requestNumber || '',
      applicantName: currentRequest?.applicantName || '',
      applicantCompany: currentRequest?.applicantCompany || '',
      nationality: currentRequest?.nationality || '',
      passportNumber: currentRequest?.passportNumber || '',
      passportExpiryDate: currentRequest?.passportExpiryDate || '',
      purpose: currentRequest?.purpose || '',
      durationDays: currentRequest?.durationDays || 30,
      requestedDate: currentRequest?.requestedDate || new Date().toISOString().split('T')[0],
      expectedArrivalDate: currentRequest?.expectedArrivalDate || '',
      passportCopyUrl: currentRequest?.passportCopyUrl || '',
      letterOfIntentUrl: currentRequest?.letterOfIntentUrl || '',
      companyCrUrl: currentRequest?.companyCrUrl || '',
      invitationLetterUrl: currentRequest?.invitationLetterUrl || '',
      visaFee: currentRequest?.visaFee || 0,
      processingFee: currentRequest?.processingFee || 0,
      totalAmount: currentRequest?.totalAmount || 0,
      currencyCode: currentRequest?.currencyCode || 'SAR',
      status: currentRequest?.status || 'Pending',
      assignedTo: currentRequest?.assignedTo || '',
      remarks: currentRequest?.remarks || '',
      invoiceId: currentRequest?.invoiceId || '',
    }),
    [currentRequest]
  );

  const methods = useForm({
    resolver: zodResolver(BusinessVisaSchema),
    defaultValues,
  });

  const {
    reset,
    watch,
    setValue,
    handleSubmit,
    formState: { isSubmitting, isDirty },
  } = methods;

  const visaFee = watch('visaFee');
  const processingFee = watch('processingFee');

  // Auto-calculate total amount
  useEffect(() => {
    const total = Number(visaFee || 0) + Number(processingFee || 0);
    setValue('totalAmount', total, { shouldDirty: false, shouldValidate: false });
  }, [visaFee, processingFee, setValue]);

  useEffect(() => {
    if (currentRequest) {
      reset(defaultValues);
      if (currentRequest.status) {
        setValue('status', normalizeStatus(currentRequest.status), {
          shouldDirty: false,
          shouldValidate: false,
        });
      }
    }
  }, [currentRequest, defaultValues, reset, setValue]);

  const normalizeDate = (v) => {
    if (!v) return undefined;
    if (typeof v === 'string') return v;
    try {
      const d = v instanceof Date ? v : new Date(v);
      return d.toISOString().split('T')[0];
    } catch {
      return String(v);
    }
  };

  const normalizeStatus = (s) => {
    if (!s) return undefined;
    const map = {
      pending: 'Pending',
      approved: 'Approved',
      processed: 'Processed',
      issued: 'Issued',
      rejected: 'Rejected',
      cancelled: 'Cancelled',
    };
    return map[String(s).toLowerCase()] ?? s;
  };
  const onSubmit = handleSubmit(async (data) => {
    try {
      const requestData = {
        applicantName: data.applicantName,
        nationality: data.nationality,
        passportNumber: data.passportNumber,
        passportExpiryDate: normalizeDate(data.passportExpiryDate),
        purpose: data.purpose,
        durationDays: data.durationDays, // already coerced by zod
        requestedDate: normalizeDate(data.requestedDate),
        visaFee: data.visaFee, // already coerced by zod
        totalAmount: data.totalAmount, // already coerced by zod
        currencyCode: data.currencyCode,
        status: data.status,
      };

      if (!currentRequest && !data.requestNumber) {
        requestData.requestNumber =
          typeof crypto !== 'undefined' && crypto.randomUUID
            ? crypto.randomUUID()
            : `${Date.now()}-${Math.random().toString(36).slice(2)}`;
      }

      // Only add optional fields if they have values
      if (typeof data.applicantCompany === 'string' && data.applicantCompany.trim()) {
        requestData.applicantCompany = data.applicantCompany.trim();
      }

      const expectedArrivalDate = normalizeDate(data.expectedArrivalDate);
      if (expectedArrivalDate) {
        requestData.expectedArrivalDate = expectedArrivalDate;
      }

      if (typeof data.passportCopyUrl === 'string' && data.passportCopyUrl.trim()) {
        requestData.passportCopyUrl = data.passportCopyUrl.trim();
      }
      if (typeof data.letterOfIntentUrl === 'string' && data.letterOfIntentUrl.trim()) {
        requestData.letterOfIntentUrl = data.letterOfIntentUrl.trim();
      }
      if (typeof data.companyCrUrl === 'string' && data.companyCrUrl.trim()) {
        requestData.companyCrUrl = data.companyCrUrl.trim();
      }
      if (typeof data.invitationLetterUrl === 'string' && data.invitationLetterUrl.trim()) {
        requestData.invitationLetterUrl = data.invitationLetterUrl.trim();
      }

      // Include processingFee even if it's 0
      if (typeof data.processingFee === 'number') {
        requestData.processingFee = data.processingFee;
      }

      if (typeof data.assignedTo === 'string' && data.assignedTo.trim()) {
        requestData.assignedTo = data.assignedTo.trim();
      }
      if (typeof data.remarks === 'string' && data.remarks.trim()) {
        requestData.remarks = data.remarks.trim();
      }
      if (typeof data.invoiceId === 'string' && data.invoiceId.trim()) {
        requestData.invoiceId = data.invoiceId.trim();
      }

      // Only include requestNumber when editing (DB generates on create)
      if (currentRequest && data.requestNumber) {
        requestData.requestNumber = data.requestNumber;
      }

      if (currentRequest) {
        await updateBusinessVisaRequest(currentRequest.id, requestData);
        toast.success('Business visa request updated successfully!');
      } else {
        await createBusinessVisaRequest(requestData);
        toast.success('Business visa request created successfully!');
      }

      router.push(paths.dashboard.hr.businessVisa.root);
    } catch (error) {
      console.error('Error saving business visa request:', error);
      toast.error(currentRequest ? 'Failed to update request' : 'Failed to create request');
    }
  });

  return (
    <Form methods={methods} onSubmit={onSubmit}>
      <Grid container spacing={3}>
        <Grid item xs={12} md={8}>
          <Stack spacing={3}>
            {/* Request Information */}
            <Card sx={{ p: 3 }}>
              <Typography variant="h6" sx={{ mb: 3 }}>
                Request Information
              </Typography>
              <Box
                sx={{
                  rowGap: 3,
                  columnGap: 2,
                  display: 'grid',
                  gridTemplateColumns: { xs: 'repeat(1, 1fr)', sm: 'repeat(2, 1fr)' },
                }}
              >
                {currentRequest && (
                  <Field.Text
                    name="requestNumber"
                    label="Request Number"
                    InputProps={{ readOnly: true }}
                  />
                )}
                <Field.Select name="status" label="Status" required>
                  <MenuItem value="Pending">Pending</MenuItem>
                  <MenuItem value="Approved">Approved</MenuItem>
                  <MenuItem value="Processed">Processed</MenuItem>
                  <MenuItem value="Issued">Issued</MenuItem>
                  <MenuItem value="Rejected">Rejected</MenuItem>
                  <MenuItem value="Cancelled">Cancelled</MenuItem>
                </Field.Select>
                <Field.DatePicker name="requestedDate" label="Requested Date" required />
                <Field.DatePicker name="expectedArrivalDate" label="Expected Arrival Date" />
                <Field.Text name="assignedTo" label="Assigned To" />
                <Field.Text name="invoiceId" label="Invoice ID" />
              </Box>
            </Card>

            {/* Applicant Information */}
            <Card sx={{ p: 3 }}>
              <Typography variant="h6" sx={{ mb: 3 }}>
                Applicant Information
              </Typography>
              <Box
                sx={{
                  rowGap: 3,
                  columnGap: 2,
                  display: 'grid',
                  gridTemplateColumns: { xs: 'repeat(1, 1fr)', sm: 'repeat(2, 1fr)' },
                }}
              >
                <Field.Text name="applicantName" label="Applicant Name" required />
                <Field.Text name="applicantCompany" label="Company Name" />
                <Field.Text name="nationality" label="Nationality" required />
                <Field.Text name="passportNumber" label="Passport Number" required />
                <Field.DatePicker name="passportExpiryDate" label="Passport Expiry Date" required />
              </Box>
            </Card>

            {/* Visa Details */}
            <Card sx={{ p: 3 }}>
              <Typography variant="h6" sx={{ mb: 3 }}>
                Visa Details
              </Typography>
              <Box
                sx={{
                  rowGap: 3,
                  columnGap: 2,
                  display: 'grid',
                  gridTemplateColumns: { xs: 'repeat(1, 1fr)', sm: 'repeat(2, 1fr)' },
                }}
              >
                <Box sx={{ gridColumn: '1 / -1' }}>
                  <Field.Text name="purpose" label="Purpose of Visit" required multiline rows={3} />
                </Box>
                <Field.Text name="durationDays" label="Duration (Days)" type="number" required />
                <Field.Text name="currencyCode" label="Currency Code" required />
                <Field.Text name="visaFee" label="Visa Fee" type="number" required />
                <Field.Text name="processingFee" label="Processing Fee" type="number" />
                <Field.Text
                  name="totalAmount"
                  label="Total Amount"
                  type="number"
                  required
                  InputProps={{ readOnly: true }}
                />
              </Box>
            </Card>

            {/* Documents */}
            <Card sx={{ p: 3 }}>
              <Typography variant="h6" sx={{ mb: 3 }}>
                Documents
              </Typography>
              <Box
                sx={{
                  rowGap: 3,
                  columnGap: 2,
                  display: 'grid',
                  gridTemplateColumns: { xs: 'repeat(1, 1fr)', sm: 'repeat(2, 1fr)' },
                }}
              >
                <Field.Text name="passportCopyUrl" label="Passport Copy URL" />
                <Field.Text name="letterOfIntentUrl" label="Letter of Intent URL" />
                <Field.Text name="companyCrUrl" label="Company CR URL" />
                <Field.Text name="invitationLetterUrl" label="Invitation Letter URL" />
              </Box>
            </Card>

            {/* Remarks */}
            <Card sx={{ p: 3 }}>
              <Typography variant="h6" sx={{ mb: 3 }}>
                Additional Information
              </Typography>
              <Field.Text name="remarks" label="Remarks" multiline rows={4} />
            </Card>
          </Stack>
        </Grid>

        <Grid item xs={12} md={4}>
          <Stack spacing={3}>
            {/* Actions */}
            <Card sx={{ p: 3 }}>
              <Stack spacing={2}>
                <LoadingButton
                  type="submit"
                  variant="contained"
                  size="large"
                  loading={isSubmitting}
                  disabled={currentRequest ? !isDirty : false}
                >
                  {currentRequest ? 'Update Request' : 'Create Request'}
                </LoadingButton>
                <LoadingButton
                  variant="outlined"
                  size="large"
                  onClick={() => router.push(paths.dashboard.hr.businessVisa.root)}
                >
                  Cancel
                </LoadingButton>
              </Stack>
            </Card>
          </Stack>
        </Grid>
      </Grid>
    </Form>
  );
}
